"""Generate NEURON_V2_SNAPSHOT.md with full embedded source code"""
import sys, datetime, os
sys.stdout.reconfigure(encoding='utf-8')

neuron = open("D:/Polygon/Git Projects/Neuron/neuron.py", encoding="utf-8").read()
html   = open("D:/Polygon/Git Projects/Neuron/templates/index.html", encoding="utf-8").read()
now    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

lines = [
"# NEURON v2 — Indian RE Intelligence Monitor",
f"**by Vipul Jakhar**  |  **Snapshot: {now}**  |  **All endpoints verified live**",
"",
"---",
"",
"## Quick Start",
"",
"```bash",
'cd "D:\\Polygon\\Git Projects\\Neuron"',
"python neuron.py",
"# Then open http://localhost:5000",
"```",
"",
"### One-time setup (already completed)",
"",
"```bash",
"pip install flask yfinance feedparser numpy requests pandas beautifulsoup4 openpyxl",
"playwright install chromium",
"```",
"",
"---",
"",
"## Project Structure",
"",
"```",
"Neuron/",
"  neuron.py                <- Flask backend (381 lines)",
"  templates/",
"    index.html             <- Full dashboard UI (1064 lines, Solarized Dark)",
"  requirements.txt",
"  start.bat                <- Windows one-click launcher",
"  NEURON_V2_SNAPSHOT.md   <- This recovery file",
"```",
"",
"---",
"",
"## Data Sources — All Free, Zero API Keys",
"",
"| Source | URL | Cache TTL | Data |",
"|--------|-----|-----------|------|",
"| MNRE Physical Progress | mnre.gov.in/en/physical-progress/ | 1 hr | Live installed capacity by sector |",
"| CEA Excel Report | cea.nic.in/.../Website.xlsx | 24 hr | National + state-wise all fuels |",
"| Yahoo Finance | yfinance library | 5 min | 14 NSE RE stocks live |",
"| RSS x7 | Mercom, PVTech, ET Energy, Saur, REGlobal, IEEFA, CleanTechnica | 5 min | Industry news + alerts |",
"| World Bank API | api.worldbank.org/v2/country/IN | 24 hr | India RE % of electricity |",
"| YouTube RSS | youtube.com/feeds/videos.xml | 10 min | Live channel video IDs |",
"| PM Surya Ghar | pmsuryaghar.gov.in | 1 hr | Rooftop solar stats (Playwright) |",
"| PM KUSUM | pmkusum.mnre.gov.in | 1 hr | Agricultural solar stats (Playwright) |",
"",
"---",
"",
"## Live Data at Time of Snapshot",
"",
"| Metric | Value | Source |",
"|--------|-------|--------|",
"| Solar Installed | 154,236 MW (154.2 GW) | MNRE |",
"| Wind Installed | 56,437 MW | MNRE |",
"| Total RE | 279,255 MW | MNRE |",
"| Total Non-Fossil | 288,035 MW | MNRE |",
"| Total India Installed | 537,264 MW | CEA |",
"| 500 GW Target Progress | 55.8% | Calculated |",
"| Intelligence Alerts Active | 11 | RSS keyword scan |",
"",
"---",
"",
"## Dashboard Tabs",
"",
"| Tab | Key Features |",
"|-----|-------------|",
"| **Overview** | 14 stock cards (NSE live), candlestick+SMA20, MNRE live capacity bars, commodities table |",
"| **Solar** | Live GW metrics from MNRE, solar leaders table, PM Surya Ghar, state-wise chart, 2030 projection |",
"| **BESS** | Deployment trajectory, 8-player table, tech mix bars, 2030 GWh projection |",
"| **Green H2** | NGHM mission KPIs, cost trajectory ($6->$1/kg), project pipeline, value chain |",
"| **Analytics** | Candlestick+Bollinger Bands, RSI/MACD/SMA indicators, 90-day polynomial projection, World Bank chart |",
"| **News & Policy** | Live RSS from 7 sources, policy milestone tracker, SECI tender tracker |",
"| **Global & Live TV** | 8 live TV channels with switching, global RE ETFs, investment chart, normalised benchmark |",
"",
"---",
"",
"## Alert System (Bell Icon, Top-Right)",
"",
"Polls every 10 minutes. Scans all RSS articles for keyword matches across 7 categories.",
"New alerts show red badge with count. Slide-out drawer from right edge.",
"",
"| Category | Trigger Keywords |",
"|----------|-----------------|",
"| SUPPLY CHAIN | polysilicon, supply chain, cell shortage, module price, wafer, backsheet, glass shortage |",
"| TRADE | tariff, anti-dumping, ALMM, BCD, AD/CVD, import duty, safeguard, trade war, customs |",
"| POLICY | PLI, VGF, SECI tender, MNRE notification, carbon credit, RPO, REC, budget allocation |",
"| BESS/GH2 | battery storage, BESS, green hydrogen, electrolyzer, GH2, hydrogen mission, NGHM |",
"| MARKET | L1 tariff, auction result, bid, capacity addition, MW commissioned, GW installed |",
"| COMPANIES | Waaree, Premier Energy, Adani Green, IREDA, NHPC, Suzlon, Tata Power, Saatvik |",
"| GLOBAL | China solar, US IRA, EU solar, IRENA report, BloombergNEF, polysilicon price |",
"",
"---",
"",
"## Live TV Channels",
"",
"| # | Channel | YouTube Channel ID | Color Accent |",
"|---|---------|-------------------|-------------|",
"| 1 | WION | UCsB-sMFo8gznkLsNt5NU0mg | #b58900 (yellow) |",
"| 2 | ET Now | UCJim7HNvOmCJRLJnQJp0czw | #268bd2 (blue) |",
"| 3 | CNBC TV18 | UC7HExiGZiGPJqOfkfANczQA | #2aa198 (cyan) |",
"| 4 | India TV | UCE_Uy-xEpFiRLmpTEkxc-LA | #859900 (green) |",
"| 5 | Bloomberg | UCIALMKvObZNtJ6AmdCLP7Lg | #dc322f (red) |",
"| 6 | DD News | UCF2MmTp-Q6HlCJDjdHWF9Rw | #6c71c4 (violet) |",
"| 7 | NewsX | UCFZIZGhSwRSGF6Mn__cTjIA | #d33682 (magenta) |",
"| 8 | Al Jazeera | UCNye-wNBqNL5ZzHSJj3l8Bg | #cb4b16 (orange) |",
"",
"---",
"",
"## NSE Stock Universe (14 Stocks)",
"",
"| Symbol | Company |",
"|--------|---------|",
"| ADANIGREEN.NS | Adani Green Energy |",
"| NHPC.NS | NHPC |",
"| NTPC.NS | NTPC |",
"| SUZLON.NS | Suzlon Energy |",
"| SWSOLAR.NS | Sterling & Wilson Solar |",
"| IREDA.NS | IREDA |",
"| SJVN.NS | SJVN |",
"| WAAREEENER.NS | Waaree Energies |",
"| PREMIENERG.NS | Premier Energies |",
"| TATAPOWER.NS | Tata Power |",
"| TORNTPOWER.NS | Torrent Power |",
"| INOXWIND.NS | Inox Wind |",
"| WEBSOL.NS | Websol Energy |",
"| BOROSIL.NS | Borosil Renewables |",
"",
"---",
"",
"## All API Endpoints",
"",
"| Route | Cache | Description |",
"|-------|-------|-------------|",
"| GET / | — | Dashboard HTML |",
"| GET /api/dashboard | 5min | Quotes + news + commodities + alerts (single boot call) |",
"| GET /api/quotes | 5min | All 14 RE stock quotes |",
"| GET /api/history/<symbol> | 5min | 1Y OHLCV history for NSE symbol |",
"| GET /api/analysis/<symbol> | 5min | Technicals + 90d projection + 6M history |",
"| GET /api/mnre_live | 1hr | MNRE physical progress scraped live |",
"| GET /api/cea_capacity | 24hr | CEA national installed capacity breakdown |",
"| GET /api/statewise | 24hr | Top 10 states + Others RE capacity from CEA Excel |",
"| GET /api/alerts | 5min | Keyword-matched intelligence alerts from RSS |",
"| GET /api/news | 5min | Latest articles from 7 RSS feeds |",
"| GET /api/live_channels | static | TV channel list with YouTube IDs |",
"| GET /api/youtube_live/<id> | 10min | Latest video ID for channel (from YouTube RSS) |",
"| GET /api/commodities | 5min | Gold, Crude, Silver, NatGas, Aluminum |",
"| GET /api/global_re | 5min | ICLN, QCLN, NEE, ENPH, SEDG quotes |",
"| GET /api/worldbank | 24hr | India renewable % from World Bank API |",
"| GET /api/pm_surya_ghar | 1hr | Rooftop solar stats via Playwright browser |",
"| GET /api/pm_kusum | 1hr | PM KUSUM stats via Playwright browser |",
"",
"---",
"",
"## Solarized Dark Theme Palette",
"",
"```",
"--bg:      #002b36   Page background",
"--bg2:     #073642   Panel / header background",
"--border:  #094554   All borders",
"--cyan:    #2aa198   Primary accent, titles",
"--green:   #859900   Positive values, BUY signal",
"--red:     #dc322f   Negative values, SELL signal",
"--yellow:  #b58900   Neutral, HOLD signal",
"--blue:    #268bd2   Info, secondary data",
"--violet:  #6c71c4   BESS / alternative",
"--orange:  #cb4b16   Warnings",
"--magenta: #d33682   Alerts / highlight",
"--base0:   #839496   Body text",
"--base01:  #586e75   Muted / labels",
"Font:      JetBrains Mono, Courier New, monospace",
"```",
"",
"---",
"",
"## Technical Notes",
"",
"- CEA URL auto-detects from report page; fallback constructs from current YYYY/MM",
"- MNRE data updates monthly from govt website (last seen: 30.04.2026)",
"- PM Surya Ghar / KUSUM are JS-heavy; Playwright Chromium required (installed)",
"- YouTube live_stream embed works for most news channels; some may show unavailable",
"- All .nic.in / .gov.in govt sites use verify=False due to SSL cert chain issues",
"- Cache is in-memory dict; cleared on server restart",
"- threaded=True on Flask allows concurrent API calls during page load",
"",
"---",
"",
"## RESTORE FROM THIS FILE",
"",
"**If any edit breaks Neuron, restore in 3 steps:**",
"",
"1. Copy the `neuron.py` code block below -> paste into `neuron.py`",
"2. Copy the `index.html` code block below -> paste into `templates/index.html`",
"3. Run: `python neuron.py` then open `http://localhost:5000`",
"",
"**No database. No config files. No environment variables needed.**",
"",
"---",
"",
"## FULL SOURCE CODE — neuron.py",
"",
"```python",
neuron,
"```",
"",
"---",
"",
"## FULL SOURCE CODE — templates/index.html",
"",
"```html",
html,
"```",
]

content = "\n".join(lines)
path = "D:/Polygon/Git Projects/Neuron/NEURON_V2_SNAPSHOT.md"
open(path, "w", encoding="utf-8").write(content)
kb = os.path.getsize(path) // 1024
print(f"Saved: {path}")
print(f"Size : {kb} KB  /  {len(content.splitlines())} lines")
